# Generated by Django 4.2 on 2026-05-28 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('flag_reason', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_status', to='ingestion.normalizedentry')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('uploaded', 'Uploaded'), ('parsed', 'Parsed'), ('edited', 'Edited'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], max_length=20)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.UUIDField()),
                ('before_state', models.JSONField(null=True)),
                ('after_state', models.JSONField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
    ]
