# Generated by Django 4.2 on 2026-05-28 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_fuel_procurement', 'SAP Fuel Procurement'), ('utility_electricity', 'Utility Electricity'), ('corporate_travel', 'Corporate Travel')], max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'file_hash')},
            },
        ),
        migrations.CreateModel(
            name='RawRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('raw_data', models.JSONField()),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='ingestion.ingestionbatch')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('activity_date', models.DateField()),
                ('description', models.TextField()),
                ('original_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('original_unit', models.CharField(max_length=50)),
                ('normalized_value', models.DecimalField(decimal_places=6, max_digits=18)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('co2e_kg', models.DecimalField(decimal_places=6, max_digits=18)),
                ('emission_factor', models.DecimalField(decimal_places=8, max_digits=18)),
                ('emission_factor_source', models.CharField(max_length=255)),
                ('source_location', models.CharField(blank=True, max_length=255)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.ingestionbatch')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('raw_row', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ingestion.rawrow')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
        ),
    ]
